### ISSUE TITLE
[Bug]: Error while trying to load `go.benjiv.com/hammer`

### ISSUE THREAD

**Issue by benjivesterby** [devnw/srv.gopkgs.org#32]
```json
{
  "prefix": "srv.gopkgs.org",
  "type": "CRITICAL",
  "timestamp": "2022-06-17T09:57:21Z",
  "error": "/hammer GET: panic while serving request: runtime error: invalid memory address or nil pointer dereference\nSTACK:\ngoroutine 7165 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65\ngo.devnw.com/gois/api.PanicHandler.func1.1()\n\t/home/runner/work/srv.gopkgs.org/srv.gopkgs.org/api/panic.go:18 +0x66\npanic({0xaaf4c0, 0x10f0db0})\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207\ngo.devnw.com/gois/api.(*DomainManager).Handler(0xc000103320, {0xc9eb20, 0xc00011e020}, 0xc0000e6d00)\n\t/home/runner/work/srv.gopkgs.org/srv.gopkgs.org/api/domain.go:265 +0x1b6\nnet/http.HandlerFunc.ServeHTTP(0xc000089c08?, {0xc9eb20?, 0xc00011e020?}, 0xc0003b5000?)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f\ngo.devnw.com/gois/api.PanicHandler.func1({0xc9eb20?, 0xc00011e020?}, 0xc000506228?)\n\t/home/runner/work/srv.gopkgs.org/srv.gopkgs.org/api/panic.go:25 +0x83\nnet/http.HandlerFunc.ServeHTTP(0xc000120700?, {0xc9eb20?, 0xc00011e020?}, 0x0?)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc0002f09b8?, {0xc9eb20, 0xc00011e020}, 0xc0000e6d00)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2462 +0x149\nnet/http.serverHandler.ServeHTTP({0x0?}, {0xc9eb20, 0xc00011e020}, 0xc0000e6d00)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2916 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0xc9f478?, 0xc00048c5a0?}, 0xc000506380?, {0xc0001581c0?}}, {0xc9eb20, 0xc00011e020}, 0xc0000e6d00)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:3523 +0x245\nnet/http.(*http2serverConn).runHandler(0xc00031e0c0?, 0x0?, 0xc000100ba0?, 0x0?)\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:5903 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:5633 +0x59b\n",
  "messages": []
}
```

**Comment by benjivesterby** [comment]
The meta-tag pointer was incorrectly pointing at `devnw` which caused a 404 and that may have been the issue

**Comment by benjivesterby** [comment]
This was solved when the cache was cleared and was due to a mis-type in the repo location
